#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_PROJECT_NAME 	"rfjammer"

#define CONFIG_HOME_PREFIX  	""//"/home/roman/data/work/ciberbob/rfjammer"
#define CONFIG_HOME_PATH		CONFIG_HOME_PREFIX "/home/root/"

#define CONFIG_BIN_DIR			CONFIG_HOME_PATH "Bin/"
#define CONFIG_CONF_DIR			CONFIG_HOME_PATH "Conf/"
#define CONFIG_SCRIPTS_DIR		CONFIG_HOME_PATH "Scripts/"

#define CONFIG_GUI_APP_NAME		"wtgui"
#define CONFIG_GUI_APP_PATH		CONFIG_BIN_DIR CONFIG_GUI_APP_NAME

#define CONFIG_WT_FILE_DIR		CONFIG_HOME_PATH "Wtgui/"
#define CONFIG_WTGUI_DOCROOT	CONFIG_WT_FILE_DIR "docroot"
#define CONFIG_WTGUI_APPROOT	CONFIG_WT_FILE_DIR "approot"
#define CONFIG_WTGUI_RESOURCES	"/usr/share/Wt/resources"

#define CONFIG_STATIC_NETCONF			CONFIG_CONF_DIR "static-net.cfg"
#define CONFIG_PARAMS_FILE_NAME			CONFIG_PROJECT_NAME ".cfg"
#define CONFIG_PARAMS_FILE_PATH			CONFIG_CONF_DIR CONFIG_PARAMS_FILE_NAME
#define CONFIG_VPN_CONF_FILE_NAME		"client.ovpn"
#define CONFIG_VPN_CONF_FILE_PATH		CONFIG_CONF_DIR CONFIG_VPN_CONF_FILE_NAME
#define CONFIG_VPN_EXAMPLE_FILE_NAME	"example.ovpn"
#define CONFIG_VPN_EXAMPLE_FILE_PATH	CONFIG_CONF_DIR CONFIG_VPN_EXAMPLE_FILE_NAME

#define CONFIG_CTLPIPE_NAME				"/tmp/ctlserver.pipe"

#define CONFIG_SPIDEV_NAME		"/dev/spidev3.0"
#define CONFIG_SI4463_IRQ_GPIO	164 // in
#define CONFIG_SI4463_CTS_GPIO	79 // in
#define CONFIG_SI4463_SDN_GPIO	77 // out
#define CONFIG_SI4463_CS_GPIO	84 // out

#define CONFIG_GREEN_LED_GPIO	74
#define CONFIG_RED_LED_GPIO		73

#define CONFIG_SIGNAL_LVL_VALUE_MAX	100

#endif /* CONFIG_H */
